spring:
  application:
    name: eurekaserviceregistry

server:
  port:8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    root: debug
    com.netflix.eureka: debug
    com.netflix.discovery: debug
