server:
  port: 9761

spring.boot.admin:
  client:
    url:
      http://eurekaserviceregistry-prod:${server.port}
    instance:
      service-base-url: http://eurekaserviceregistry-prod:${server.port}

eureka:
  instance:
    hostname: eurekaserviceregistry-prod
    non-secure-port: ${server.port}
  client:
    enabled: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

logging:
  level:
    root: info
