server.port: 8761

spring.boot.admin:
  client:
    url:
      http://eurekaserviceregistry-dev:${server.port}
    instance:
      service-base-url: http://eurekaserviceregistry-dev:${server.port}

eureka:
  instance:
    hostname: eurekaserviceregistry-dev
    non-secure-port: ${server.port}
  client:
    enabled: true
    service-url:
      defaultZone: http://${app.login.admin.username}:${app.login.admin.password}@${eureka.instance.hostname}:${server.port}/eureka

logging:
  level:
    root: info
    com.netflix.eureka: debug
    com.netflix.discovery: debug
