server.port: 7761

appconfig:
  cors:
    # Allow Ionic for JHipster by default (* no longer allowed in Spring Boot 2.4+)
    allowed-origins: 'http://localhost:7761,https://localhost:7001,http://localhost:9000,https://localhost:9000,http://localhost:4200,https://localhost:4200'
    # Enable CORS when running in GitHub Codespaces
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${spring.application.name}-alert,X-${spring.application.name}-error,X-${spring.application.name}-params'
    allow-credentials: true
    max-age: 1800

spring.boot.admin:
  client:
    url:
      http://localhost:${server.port}
    instance:
      service-base-url: http://localhost:${server.port}

eureka:
  dashboard:
  instance:
    hostname: localhost
    non-secure-port: ${server.port}
  client:
    enabled: true
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://${app.login.admin.username}:${app.login.admin.password}@${eureka.instance.hostname}:${server.port}/eureka

logging:
  file:
    name: ${spring.application.name}.log
  pattern:
    file: "%black(%d{ISO8601}) %highlight(%-5level) %yellow(%c{2}): %highlight(%msg%n%throwable)"
  level:
    root: info
    web: info
    com.stoi: debug
    com.netflix.eureka: info
    com.netflix.discovery: info
    org.springframework.web.servlet.mvc.method.annotation: trace
    org.springframework.security.web: trace
    org.springframework.cloud.netflix.eureka.serviceregistry: trace
#    org.springframework.web: debug
#    org.springframework.web.servlet.handler.SimpleUrlHandlerMapping: trace
