server:
  port: 9761

eureka:
  dashboard:
    path: /admin/eureka
  instance:
    hostname: eurekaserviceregistry-prod
    non-secure-port: ${server.port}
  client:
    enabled: true
    server:
      waitTimeInMsWhenSyncEmpty: 0
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

logging:
  level:
    root: info
    com.netflix.eureka: debug
    com.netflix.discovery: debug
