# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'

services:
  eurekaserviceregistry-prod:
    image: eurekaserviceregistry
    ports:
      - 127.0.0.1:9761:9761
    networks:
      - fightcluck-network-prod
    environment:
      #      server.port: 9761
      SPRING_PROFILES_ACTIVE: prod
      _JAVA_OPTIONS: -Xmx512m -Xms256m

networks:
  fightcluck-network-prod:
    name: fightcluck-network-prod
    driver: bridge
    external: true